### ISSUE TITLE
Time zone?

### ISSUE THREAD

**Issue by asteelebush** [scaratozzolo/MouseTools#11]
What is the time zone of the wait time data? Trying to convert it to central time.

 '80010170': {'name': "Mickey's PhilharMagic",
  'status': 'Operating',
  'wait_time': 10,
  'last_updated': datetime.datetime(2021, 9, 14, 13, 18, 18, 801000),
  'entityType': 'Attraction'},

**Comment by scaratozzolo** [comment]
The time zone should be the local time of the destination. So Disney World is EST and Disneyland is PST.

**Comment by asteelebush** [comment]
that's what i expected, but looks like the above is saying the wait time was last updated at 13:18 PST (disneyland). The time in disneyland right now is 9:19...

**Comment by scaratozzolo** [comment]
That is weird but if that's what's being reported than that's what's being reported. When I have some more time I'll look into it and make sure it's actually the correct time zone.
