### ISSUE TITLE
Can't install anymore -  I think package is failing on netrc library..

### ISSUE THREAD

**Issue by redrockanalytics** [scaratozzolo/MouseTools#12]
have tried on multiple versions of Python3 and cannot install library!!!

**Comment by scaratozzolo** [comment]
I'm sorry, but I haven't looked at this project in a while. The only package it depends on is the requests library. Can you please give some more details such as what versions of python you're trying to run on and/or any error logs.

**Comment by redrockanalytics** [comment]
Hi Scott.  I realize it only requires Requests but I invite you to try to :

Pip install MouseTools.

  It keeps hanging. I’ve tried on new machines with no Python installed and ones that had Python that stopped working.   3.6.x 3.8.x. 3.11.1. Nothing works

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by redrockanalytics** [comment]
My belief when I ran it with -V switch is that it is hanging on netrc. I don’t know why.    I

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by redrockanalytics** [comment]
No errors come up. It just hangs.   Try it for yourself.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
