### ISSUE TITLE
Hangs on import MouseTools

### ISSUE THREAD

**Issue by steve-cicco** [scaratozzolo/MouseTools#7]
Hello,

I found your project while looking for a way to get realtime Disney wait times to display on an LED matrix.  Thought this would be a fun way to bring some Disney magic into my home during COVID.

I have been fighting with this for two nights now and feel really stupid.  After installing and running it hangs on `import MouseTools`.  I was patient the first few times as instructed and after an hour I noticed that MouseTools.db stays at 0KB so I'm not sure if it's even getting to Disney's site.  I know that's not much to go on but any tips would be greatly appreciated.

Thanks!
Steve

**Comment by alejandroguzmancabrera** [comment]
I let it run all night as well and had the same result... even running py -m pydoc MouseTools hangs

**Comment by scaratozzolo** [comment]
My semester just ended so I'll try to take a look over my break.

**Comment by scaratozzolo** [comment]
I should have something working within the next few days.

**Comment by scaratozzolo** [comment]
I put a beta version on pypi. I would recommend uninstall your current version of MouseTools and then installing the beta with "pip install MouseTools==2.1.0b1". This removes the whole database stuff as I wasn't able to find a way to connect again. I assume credentials changed or something. Some functions were also changed and others removed and I haven't been able to fully test. So just reply to this thread with any comments or issues.

**Comment by steve-cicco** [comment]
Quickly checked it out on my lunch break and it's perfect!  I wanted to be able to iterate through each WDW park's attractions and see their wait time and this does the trick:

`for park_id in MouseTools.ids.WDW_PARK_IDS:
    park = MouseTools.Park(park_id)
    print(park.get_name())
    for attr_id in MouseTools.Park(park_id).get_attraction_wait_times():
        attr = MouseTools.Attraction(attr_id)
        print(attr.get_name())
        print(attr.get_wait_time())`

I have to get back to my real job but cannot wait to get this info onto my LED matrix hopefully this weekend.  Thanks so much!!!

**Comment by scaratozzolo** [comment]
You could also do something like this:

```python
for park_id in MouseTools.ids.WDW_PARK_IDS:
     park = MouseTools.Park(park_id)
     for id, values in park.get_wait_times_detailed().items():
         print(f"{values['name']}: {values['wait_time']}")

```

get_wait_times_detailed() returns a dictionary of dictionaries with the following key:value pairs:

{
     id: {
          name,
          status
          wait_time
          last_updated
          entityType
     }
}

An example:

{
     '80069748': {
          'name': 'Country Bear Jamboree', 
          'status': 'Operating',
           'wait_time': None, 
          'last_updated': datetime.datetime(2021, 1, 11, 16, 2, 7, 6000), 
          'entityType': 'Attraction'}
}

**Comment by steve-cicco** [comment]
Even better!

I couldn't wait and got everything transferred to my Pi and LED matrix.  Cannot wait to get this formatted with text that fits, park and ride logos, etc.

Thanks again!

![IMG_4243](https://user-images.githubusercontent.com/18751786/104258368-0b0fe600-5445-11eb-9dc1-22a95673826e.png)
